# Generated by Django 5.2.6 on 2025-09-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messege',
            name='message_type',
            field=models.CharField(default='text', max_length=100),
        ),
    ]
