# Generated by Django 5.2.6 on 2025-11-27 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_userkeys_chatkeys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messege',
            name='message_type',
        ),
        migrations.CreateModel(
            name='MessageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='message_images/')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chats.messege')),
            ],
            options={
                'verbose_name': 'Message Image',
                'verbose_name_plural': 'Message Images',
            },
        ),
    ]
